In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

0      False
1      False
2      False
3      False
4      False
       ...  
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [7]:
df.duplicated().sum()

1

In [8]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [39]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [16]:
df['sepal_length'].unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [24]:
df['sepal_length'] = lb.fit_transform(df['sepal_length'])

In [25]:
df['sepal_length'].unique()

array([ 8,  6,  4,  3,  7, 11,  1,  5,  0, 15, 14,  9, 12,  2, 10, 27, 21,
       26, 22, 20, 23, 16, 17, 18, 13, 24, 19, 25, 28, 32, 30, 29, 33, 31,
       34], dtype=int64)

In [20]:
df['petal_length'].unique()

array([1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1. , 1.9, 4.7, 4.5, 4.9, 4. ,
       4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5. , 3.8, 3.7,
       5.1, 3. , 6. , 5.9, 5.6, 5.8, 6.6, 6.3, 6.1, 5.3, 5.5, 6.7, 6.9,
       5.7, 6.4, 5.4, 5.2])

In [26]:
df['petal_length'] = lb.fit_transform(df['petal_length'])

In [27]:
df['petal_length'].unique()

array([ 4,  3,  5,  7,  6,  1,  2,  0,  8, 23, 21, 25, 16, 22, 10, 15, 11,
       18, 12, 20, 17, 24, 19, 26, 14, 13, 27,  9, 36, 35, 32, 34, 40, 38,
       37, 29, 31, 41, 42, 33, 39, 30, 28], dtype=int64)

In [28]:
df['petal_width'].unique()

array([0.2, 0.4, 0.3, 0.1, 0.5, 0.6, 1.4, 1.5, 1.3, 1.6, 1. , 1.1, 1.8,
       1.2, 1.7, 2.5, 1.9, 2.1, 2.2, 2. , 2.4, 2.3])

In [29]:
df['petal_width'] = lb.fit_transform(df['petal_width'])

In [37]:
df['petal_width'].unique()

array([ 1,  3,  2,  0,  4,  5, 10, 11,  9, 12,  6,  7, 14,  8, 13, 21, 15,
       17, 18, 16, 20, 19], dtype=int64)

In [31]:
df['sepal_width'].unique()

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, 3.7, 4. , 4.4, 3.8, 3.3,
       4.1, 4.2, 2.3, 2.8, 2.4, 2.7, 2. , 2.2, 2.5, 2.6])

In [32]:
df['sepal_width'] = lb.fit_transform(df['sepal_width'])

In [33]:
df['sepal_width'].unique()

array([14,  9, 11, 10, 15, 18, 13,  8, 16, 19, 22, 17, 12, 20, 21,  2,  7,
        3,  6,  0,  1,  4,  5], dtype=int64)